# reference: https://python-poetry.org/docs/pyproject/

[tool.poetry]
name = "kdemo"
version = "0.1.0"
description = "Kubeflow demo for the MLOps Community Meetup at Luxembourg"
authors = ["Médéric Hurier (Fmind) <mederic.hurier@fmind.dev>"]
repository = "https://github.com/fmind/kubeflow-demo"
readme = "README.md"
license = "MIT"
packages = [{include = "kdemo", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
kfp = "2.0.0b13"
pandas = "^2.0.0"
scikit-learn = "^1.2.2"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
invoke = "^2.0.0"
ipykernel = "^6.22.0"
ipython = "^8.12.0"
isort = "^5.12.0"
mypy = "^1.2.0"
pylint = "^2.17.2"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.mypy]
ignore_missing_imports = true

[tool.pylint.MASTER]
disable = []
max-line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
